# ansible-playbook playboooks/01_copy_playbook.yml -u iaktas
---
- hosts: virtual-machine
  tasks:
    - name: Copy files from task
      copy:
        src: /home/yildirim/key.text
        dest: /home/sanal/deneme
        owner: sanal
        group: sanal
        mode: '0644'  
...

